// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1WyKwv6e4odnWMDZYPqds70kqDOaW0NQ',
    appId: '1:4444257848:web:c4322905416f98c75bb0cd',
    messagingSenderId: '4444257848',
    projectId: 'fir-flutter-88b4c',
    authDomain: 'fir-flutter-88b4c.firebaseapp.com',
    storageBucket: 'fir-flutter-88b4c.firebasestorage.app',
    measurementId: 'G-R4M4W2NH7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi7YRavFT8pLf_IOYT7JqH8Zl2mB7EQgw',
    appId: '1:4444257848:android:99384cd2d2d6d6565bb0cd',
    messagingSenderId: '4444257848',
    projectId: 'fir-flutter-88b4c',
    storageBucket: 'fir-flutter-88b4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuUQddKVDxcUngJp4M5w4URF1_bZ3Aud4',
    appId: '1:4444257848:ios:3543c8652261035b5bb0cd',
    messagingSenderId: '4444257848',
    projectId: 'fir-flutter-88b4c',
    storageBucket: 'fir-flutter-88b4c.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuUQddKVDxcUngJp4M5w4URF1_bZ3Aud4',
    appId: '1:4444257848:ios:3543c8652261035b5bb0cd',
    messagingSenderId: '4444257848',
    projectId: 'fir-flutter-88b4c',
    storageBucket: 'fir-flutter-88b4c.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1WyKwv6e4odnWMDZYPqds70kqDOaW0NQ',
    appId: '1:4444257848:web:388de52255c60b1b5bb0cd',
    messagingSenderId: '4444257848',
    projectId: 'fir-flutter-88b4c',
    authDomain: 'fir-flutter-88b4c.firebaseapp.com',
    storageBucket: 'fir-flutter-88b4c.firebasestorage.app',
    measurementId: 'G-5YSP0WD4Y8',
  );
}
